### ISSUE TITLE
`FastStringServiceFactory` class not found exception in `ProjectBuilder` based tests after upgrade to latest Gradle master

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#1131]
`TaskContainerDslTest` and `NamedContainerDslTest` started failing after upgrading to a distribution built from latest Gradle master with:
```
java.lang.NoClassDefFoundError: org/gradle/internal/impldep/org/apache/groovy/json/FastStringServiceFactory
	at org.gradle.initialization.DefaultGradleApiSpecProvider.getExportedClasses(DefaultGradleApiSpecProvider.java:29)
	at org.gradle.initialization.GradleApiSpecAggregator.mergeSpecsOf(GradleApiSpecAggregator.java:63)
	at org.gradle.initialization.GradleApiSpecAggregator.aggregate(GradleApiSpecAggregator.java:45)
	at org.gradle.initialization.DefaultClassLoaderRegistry.apiSpecFor(DefaultClassLoaderRegistry.java:44)
	at org.gradle.initialization.DefaultClassLoaderRegistry.restrictToGradleApi(DefaultClassLoaderRegistry.java:35)
	at org.gradle.initialization.DefaultClassLoaderRegistry.<init>(DefaultClassLoaderRegistry.java:29)
	at org.gradle.internal.service.scopes.GlobalScopeServices.createClassLoaderRegistry(GlobalScopeServices.java:216)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:35)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:821)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:774)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:568)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:625)
	at org.gradle.internal.service.DefaultServiceRegistry.applyConfigureMethod(DefaultServiceRegistry.java:188)
	at org.gradle.internal.service.DefaultServiceRegistry.findProviderMethods(DefaultServiceRegistry.java:170)
	at org.gradle.internal.service.DefaultServiceRegistry.addProvider(DefaultServiceRegistry.java:244)
	at org.gradle.internal.service.ServiceRegistryBuilder.build(ServiceRegistryBuilder.java:52)
	at org.gradle.testfixtures.internal.ProjectBuilderImpl.getGlobalServices(ProjectBuilderImpl.java:155)
	at org.gradle.testfixtures.internal.ProjectBuilderImpl.createProject(ProjectBuilderImpl.java:110)
	at org.gradle.testfixtures.ProjectBuilder.build(ProjectBuilder.java:116)
```

**Comment by eskatos** [comment]
Failing tests: https://scans.gradle.com/s/l2yw3cygo73se/tests
`testRuntimeClasspath`: https://scans.gradle.com/s/lwun42b3cojs6/console-log?task=:provider:dependencies
`testRuntimeClasspath.files`https://scans.gradle.com/s/s6itzikomqbeu/console-log?task=:provider:printTestClasspath

**Comment by wolfs** [comment]
@lptr I guess this is related to the Groovy update?

**Comment by eskatos** [comment]
The Gradle classloading setup in `ProjectBuilder` is wrong because of our transform of the `gradleApi()` generated jar that produces a directory.

See
https://github.com/gradle/gradle/blob/182ec6996296d5b21128c34657cd17f577b731bf/subprojects/core/src/main/java/org/gradle/internal/service/scopes/GlobalScopeServices.java#L211-L217

And:
https://github.com/gradle/gradle/blob/182ec6996296d5b21128c34657cd17f577b731bf/subprojects/core/src/main/java/org/gradle/internal/installation/GradleRuntimeShadedJarDetector.java#L48
