### ISSUE TITLE
Custom plugin DSL cannot be compiled in Kotlin

### ISSUE THREAD

**Issue by jk1** [gradle/kotlin-dsl#175]
Hello. I'm currently trying to make my custom Gradle plugin compatible with Kotlin-scripted build configs. It seems like Kotlin compiler fails to infer enough type information for DSL to compile. I'd appreciate an advice on how can I make Groovy-Kotlin interop work in this case.

The plugin introduces a custom dependency repository, a subclass of IvyArtifactRepository. Here's how it's done atm in plugin code (Groovy):
````
// called from plugin apply() method
private void addCustomRepoTo(Project project) {
        def repositories = project.repositories
        DefaultRepositoryHandler handler = repositories as DefaultRepositoryHandler
        repositories.ext.customServer = { Closure configureClosure ->
                def closure = new ClosureBackedAction<IvyArtifactRepository>(configureClosure)
                handler.addRepository(new CustomRepository(...), "CustomServer", closure)
            }
        }
    }
````
In build.gradle it can be used as follows:
````
repositories {
    customServer {
        url = 'https://url.domain.com'
    }
}
````
Pretty simple thing, right? And here's how I'm trying to use in in build.gradle.kts:
````
plugins.apply("...")

repositories {
    customServer {
        setUrl("https://url.domain.com")
    }
}
````
only to receive the following error:
````
 Caused by: java.lang.AssertionError: No resolved call for 'customServer{
          setUrl("https://url.domain.com")
      }' at (19,5) in /home/jk1/Projects/consumer/build.gradle.kts
        at org.jetbrains.kotlin.resolve.calls.callUtil.CallUtilKt.getResolvedCallWithAssert(callUtil.kt:187)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.visitCallExpression(ExpressionCodegen.java:2625)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.visitCallExpression(ExpressionCodegen.java:120)
        at org.jetbrains.kotlin.psi.KtCallExpression.accept(KtCallExpression.java:35)
        at org.jetbrains.kotlin.codegen.CodegenStatementVisitor.visitKtElement(CodegenStatementVisitor.java:31)
        at org.jetbrains.kotlin.codegen.CodegenStatementVisitor.visitKtElement(CodegenStatementVisitor.java:22)
        at org.jetbrains.kotlin.psi.KtVisitor.visitExpression(KtVisitor.java:178)
        at org.jetbrains.kotlin.psi.KtVisitor.visitReferenceExpression(KtVisitor.java:194)
        at org.jetbrains.kotlin.psi.KtVisitor.visitCallExpression(KtVisitor.java:270)
        at org.jetbrains.kotlin.psi.KtCallExpression.accept(KtCallExpression.java:35)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.genQualified(ExpressionCodegen.java:293)
        ... 104 more
````
My best guess is that extension method is being added way too late for the compiler to know about it.

**Comment by jk1** [comment]
Thank you for looking into this. As FAQ claims plugins to be compatible out of the box

> Will existing plugins still work when I write my build logic in Kotlin?
> Yes, they will continue to work without a problem. 

I was expecting to find some sort of import implemented already, but now it's clear this is yet to come.
Extension method approach looks promising though, worth giving a try.

> You are using internal APIs (DefaultRepositoryHandler) and this code might break at any point.

Not sure if I have a choice here. RepositoryHandler interface doesn't expose any public API methods to add custom repositories.

**Comment by oehme** [comment]
Existing plugins work, but not everything will be as convenient, at least until we implement some of the more advanced features like custom extension methods.

Custom repositories are not yet supported. If yours is a special case of an ivy repo you could use delegation instead of inheritance, i.e. delegate to the ivy {} method.

**Comment by bamboo** [comment]
Closing as answered.
