### ISSUE TITLE
Intellij cannot resolve imports for libraries in internal corporate repositories

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#251]
This is in a subproject of a multi-project build:

```kotlin
// This import can't be resolved.
import io.swagger.codegen.config.CodegenConfigurator
buildscript {
    applyFrom("${rootProject.projectDir}/sharedValues.gradle.kts")
    val configureRepository : (Any) -> Unit by extra
    configureRepository.invoke(repositories) // Configures all of the corporate repositories

    dependencies {
        // This is a custom internally published version of this library
        classpath("io.swagger:swagger-codegen:${extra.get("swaggerCodegenVersion")}")
    }
}
```

Here is the stack trace from the intellij log:
```
2017-01-19 13:13:36,145 [82569780]  ERROR - pplication.impl.LaterInvocator - Resolver for 'completion/highlighting in ScriptModuleInfo(project=Project '/Users/jonathanleitschuh/work/git/plexxicontrol' PlexxiControl, scriptFile=file:///Users/jonathanleitschuh/work/git/plexxicontrol/PlexxiSwagger/PlexxiSwagger.gradle.kts, scriptDefinition=org.jetbrains.kotlin.script.KotlinScriptDefinitionFromAnnotatedTemplate@42c72c71) for files PlexxiSwagger.gradle.kts for platform JVM' does not know how to resolve LibraryInfo(libraryName=Gradle: io.swagger:swagger-codegen:2.2.2-plexxi-SNAPSHOT) 
java.lang.AssertionError: Resolver for 'completion/highlighting in ScriptModuleInfo(project=Project '/Users/jonathanleitschuh/work/git/plexxicontrol' PlexxiControl, scriptFile=file:///Users/jonathanleitschuh/work/git/plexxicontrol/PlexxiSwagger/PlexxiSwagger.gradle.kts, scriptDefinition=org.jetbrains.kotlin.script.KotlinScriptDefinitionFromAnnotatedTemplate@42c72c71) for files PlexxiSwagger.gradle.kts for platform JVM' does not know how to resolve LibraryInfo(libraryName=Gradle: io.swagger:swagger-codegen:2.2.2-plexxi-SNAPSHOT)
	at org.jetbrains.kotlin.analyzer.ResolverForProjectImpl.descriptorForModule(AnalyzerFacade.kt:104)
	at org.jetbrains.kotlin.analyzer.ResolverForProjectImpl.descriptorForModule(AnalyzerFacade.kt:69)
	at org.jetbrains.kotlin.analyzer.ResolverForProject.resolverForModule(AnalyzerFacade.kt:48)
	at org.jetbrains.kotlin.idea.caches.resolve.ProjectResolutionFacade.resolverForModuleInfo(ProjectResolutionFacade.kt:48)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionFacadeImpl.getFrontendService(ResolutionFacadeImpl.kt:86)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionFacadeImpl.getFrontendService(ResolutionFacadeImpl.kt:82)
	at org.jetbrains.kotlin.idea.caches.resolve.JavaResolutionUtils.getJavaDescriptorResolver(JavaResolveExtension.kt:108)
	at org.jetbrains.kotlin.idea.caches.resolve.JavaResolutionUtils.getJavaClassDescriptor(JavaResolveExtension.kt:54)
	at org.jetbrains.kotlin.idea.caches.resolve.JavaResolutionUtils.resolveToDescriptor(JavaResolveExtension.kt:102)
	at org.jetbrains.kotlin.idea.caches.resolve.JavaResolutionUtils.resolveToDescriptor$default(JavaResolveExtension.kt:94)
	at org.jetbrains.kotlin.idea.core.KotlinIndicesHelper.getJvmClassesByName(KotlinIndicesHelper.kt:206)
	at org.jetbrains.kotlin.idea.quickfix.OrdinaryImportFixBase.fillCandidates(ImportFix.kt:250)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase.computeSuggestionsForName(ImportFix.kt:178)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase.computeSuggestions(ImportFix.kt:148)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase$suggestions$2.invoke(ImportFix.kt:93)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase$suggestions$2.invoke(ImportFix.kt:84)
	at org.jetbrains.kotlin.utils.CachedValueProperty.getValue(CachedValueProperty.kt:31)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase.getSuggestions(ImportFix.kt)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase.isAvailable(ImportFix.kt:119)
	at com.intellij.codeInsight.daemon.impl.ShowAutoImportPass.a(ShowAutoImportPass.java:143)
	at com.intellij.codeInsight.daemon.impl.ShowAutoImportPass.addImports(ShowAutoImportPass.java:90)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:91)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:116)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:126)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.codeInsight.daemon.impl.ShowAutoImportPass.doApplyInformationToEditor(ShowAutoImportPass.java:77)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.applyInformationToEditor(TextEditorHighlightingPass.java:115)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService.a(PassExecutorService.java:500)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by JLLeitschuh** [comment]
Its seems that this was resolved by clearing my cache and restarting Intellij.
I don't think this should be required to fix this problem though.

**Comment by JLLeitschuh** [comment]
This seems to be an intermittent problem.
Sometimes when I invalidate and restart everything works but other times it fails to resolve the imported symbol name.

**Comment by bamboo** [comment]
Closing as non reproducible. 

If it's still happening on your side it would be better to open an issue in the Intellij issue tracker.

**Comment by JLLeitschuh** [comment]
I'm not seeing this problem anymore.
