### ISSUE TITLE
Samples failed on incorrect gradle URL

### ISSUE THREAD

**Issue by Hubbitus** [gradle/kotlin-dsl#391]
`hello-kotlin` sample:

```
./gradlew
```
```
Downloading https://services.gradle.org/distributions-snapshots/gradle-4.0-20170523130707+0000-bin.zip

Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle.org/distributions-snapshots/gradle-4.0-20170523130707+0000-bin.zip
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
        at org.gradle.wrapper.Download.download(Download.java:51)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

**Comment by Hubbitus** [comment]
It looks it like so [from February](https://discuss.kotlinlang.org/t/pre-release-version-problem-with-kotlin-in-intellij/2311/2?u=hubbitus).

**Comment by Hubbitus** [comment]
Eeh, it seems it is IntelliJ Idea replace 
`distributionUrl=https\://services.gradle.org/distributions-snapshots/gradle-4.0-20170523130707+0000-bin.zip`
to incorrect `distributionUrl=https\://repo.gradle.org/gradle/dist-snapshots/gradle-script-kotlin-4.0-20170523130707+0000-all.zip` on project import or refresh.

It works with console `./gradlew`.

How it may be fixed?

**Comment by bamboo** [comment]
Fixed in `master` and `develop`.
