### ISSUE TITLE
Using object notation causes an exception due to looking for a constructor

### ISSUE THREAD

**Issue by hzsweers** [gradle/kotlin-dsl#461]
I have a `dependencies.gradle.kts` file that I'd like to define dependencies in. To make things more readable and autocompleting, I would like to define them like this:

```kotlin
object Versions {
  val support = "26.0.0"
}

object Deps {
  object android {
    val appcompat = "com.android.support:appcompat-v7:${Versions.support}"
  }
}
```

### Expected Behavior

That this should work fine

### Current Behavior

I get this crash:

```
Caused by: java.lang.UnsupportedOperationException: Don't know how to generate outer expression for private constructor build() defined in Dependencies_gradle.Deps.build[DefaultClassConstructorDescriptor@1b99b45]
        at org.jetbrains.kotlin.codegen.context.ConstructorContext.getOuterExpression(ConstructorContext.java:44)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.generateScriptReceiver(ExpressionCodegen.java:2462)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.generateReceiverValue(ExpressionCodegen.java:2409)
        at org.jetbrains.kotlin.codegen.StackValue.genReceiver(StackValue.java:538)
        at org.jetbrains.kotlin.codegen.StackValue.receiver(StackValue.java:517)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.putReceiverAndInlineMarkerIfNeeded(ExpressionCodegen.java:2220)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2150)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2138)
        at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:44)
        at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:23)
        at org.jetbrains.kotlin.codegen.OperationStackValue.putSelector(StackValue.kt:65)
        at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:106)
        at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:99)
        at org.jetbrains.kotlin.codegen.StackValue$StackValueWithSimpleReceiver.store(StackValue.java:1696)
        at org.jetbrains.kotlin.codegen.StackValue$Property.store(StackValue.java:1286)
        at org.jetbrains.kotlin.codegen.StackValue.store(StackValue.java:128)
        at org.jetbrains.kotlin.codegen.MemberCodegen.initializeProperty(MemberCodegen.java:493)
        at org.jetbrains.kotlin.codegen.MemberCodegen.generateInitializers(MemberCodegen.java:466)
        at org.jetbrains.kotlin.codegen.ImplementationBodyCodegen.generateInitializers(ImplementationBodyCodegen.java:1063)
        at org.jetbrains.kotlin.codegen.ImplementationBodyCodegen.generatePrimaryConstructorImpl(ImplementationBodyCodegen.java:1002)
        at org.jetbrains.kotlin.codegen.ImplementationBodyCodegen.access$200(ImplementationBodyCodegen.java:95)
        at org.jetbrains.kotlin.codegen.ImplementationBodyCodegen$1.doGenerateBody(ImplementationBodyCodegen.java:916)
        at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$CodegenBased.generateBody(FunctionGenerationStrategy.java:69)
        at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:486)
        at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:249)
        at org.jetbrains.kotlin.codegen.ImplementationBodyCodegen.generatePrimaryConstructor(ImplementationBodyCodegen.java:912)
        at org.jetbrains.kotlin.codegen.ImplementationBodyCodegen.generateConstructors(ImplementationBodyCodegen.java:391)
        ... 167 more
```

### Context

See above

### Steps to Reproduce (for bugs)

I'm able to repro with the above

### Your Environment

 * Build scan URL: 
Kotlin gradle script version `gradle-kotlin-dsl-4.1-20170712173431+0000-all`
Android Gradle Plugin 3.0.0-beta2

**Comment by hzsweers** [comment]
Ping? Not sure if this got buried but seems like a fairly straightforward issue otherwise (even if it's just an ack)

**Comment by eskatos** [comment]
Hi @hzsweers,

I just copy pasted your snippet in one of my build scripts and referenced it from a dependency declaration. It worked. Maybe I'm doing something a bit different than you. Could you post a complete reproducer build?

**Comment by hzsweers** [comment]
interesting! let me try on a more recent version in my project again to be sure

**Comment by hzsweers** [comment]
Ok I'm still able to repro it. Another factor is that I'm applying this file from another build.gradle file via `applyFrom(rootProject.file("gradle/dependencies.gradle.kts"))`. If that doesn't repro it, happy to add you or someone from your team to the side project repo if you want a repro case.

**Comment by eskatos** [comment]
Yep, a complete reproducer will greatly help us track down the issue faster!

**Comment by hzsweers** [comment]
Ok - I've added you to the repo (check your email). The branch is `z/ktsgradlescript`. It's a pretty vanilla android project, just try assembling the `app2` module

**Comment by eskatos** [comment]
@hzsweers, I'm not sure what the underlying cause is, the error message provided by the Kotlin compiler is definitely not helpful to me ; but if I comment all usage of your `String.execute` extension found at the bottom of your `dependencies.gradle.kts` file then the Kotlin DSL script compiles fine.

BTW, types defined in an applied script won't be visible from the applying script, this is not supported yet (implied by #427). In the meantime you could move those types into `buildSrc` instead so they'll be visible to all your projects build scripts.
