### ISSUE TITLE
"Too many open files in system" exceptions when running check task on Mac

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#595]
I'm running the command `./gradlew check --parallel` like the PR checklist asks you to run for this project.

### Expected Behavior
The check task should succeed.

### Current Behavior

Running the above command starts giving you exceptions like this:
```
    BUILD FAILED in 0s
        at org.gradle.testkit.runner.internal.ToolingApiGradleExecutor.run(ToolingApiGradleExecutor.java:154)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:285)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:234)
        at org.gradle.kotlin.dsl.fixtures.AbstractIntegrationTest.build(AbstractIntegrationTest.kt:109)
        at org.gradle.kotlin.dsl.samples.TaskDependenciesSampleTest.mixItUp(TaskDependenciesSampleTest.kt:27)

        Caused by:
        org.gradle.tooling.GradleConnectionException: Could not execute build using Gradle installation '/Users/jonathanleitschuh/personal/git/kotlin-dsl/build/custom/gradle-4.4-20171114142330+0000'.
            at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:55)
            at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
            at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:41)
            at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
            at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
            at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
            at java.lang.Thread.run(Thread.java:745)
            at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
            at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:77)
            at org.gradle.testkit.runner.internal.ToolingApiGradleExecutor.run(ToolingApiGradleExecutor.java:130)
            ... 4 more

            Caused by:
            org.gradle.api.UncheckedIOException: java.io.IOException: Too many open files in system

                Caused by:
                java.io.IOException: Too many open files in system

```

### Context

This makes it hard to contribute because you can't run the tests locally.

Are there other flags that people build the repo should be using when running tests?

### Your Environment

This (kotlin-dsl) project.

```
------------------------------------------------------------
Gradle 4.4-20171114142330+0000
------------------------------------------------------------

Build time:   2017-11-14 14:23:30 UTC
Revision:     cb3d7cdae7795a21e9be353843ddd6676261403c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Mac OS X 10.12.6 x86_64
```

**Comment by eskatos** [comment]
Building in parallel is very file descriptor demending. If you have other running apps that keep a lot of file descriptors open at the same time you may encounter this issue (Chrome & Slack are known to be file descriptor ogres).

You can change your system's limits, see e.g. https://superuser.com/a/443168

**Comment by JLLeitschuh** [comment]
This is really good information. Thank you for this information. Is there any downside to increasing the number of file descriptors your system can have open at one time?

**Comment by eskatos** [comment]
Closing as answered.
