### ISSUE TITLE
Incompatible with Android Gradle Plugin 3.1.x

### ISSUE THREAD

**Issue by hzsweers** [gradle/kotlin-dsl#708]
The DSL currently is incompatible with android gradle plugin 3.1.x, which is currently in beta and soon to be released.

### Expected Behavior

It should work without build/configuration failures

### Current Behavior

It fails with the following stacktrace during configuration

```
Caused by: java.lang.IllegalAccessError: tried to access class com.google.common.cache.LocalCache$Values from class com.google.common.cache.LocalCache
        at com.google.common.cache.LocalCache.values(LocalCache.java:4473)
        at com.android.builder.profile.ProcessProfileWriter.finishAndMaybeWrite(ProcessProfileWriter.java:135)
        at com.android.builder.profile.ProcessProfileWriterFactory.shutdownAndMaybeWrite(ProcessProfileWriterFactory.java:52)
        at com.android.build.gradle.internal.profile.ProfilerInitializer$ProfileShutdownListener.completed(ProfilerInitializer.java:128)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:370)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:352)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)

```

### Context

It fails my builds at configuration-time if I try to use kotlin gradle script

### Steps to Reproduce (for bugs)

You can use this branch on this project. In Android studio canary for 3.1.0-beta1, it reproduces on command line and in the IDE. https://github.com/hzsweers/CatchUp/tree/z/settingsgradlekts

### Your Environment

 * Build scan URL: Unavailable because it fails to build.

**Comment by eskatos** [comment]
Thanks for the report @hzsweers 

I can reproduce on your repo: https://scans.gradle.com/s/b5ma24efnnfca
The only Gradle Kotlin DSL file there is the root  `settings.gradle.kts` file.
I tried porting it back to Groovy to rule out any issue in the Gradle Kotlin DSL.
And the build fails with the exact same error: https://gradle.com/s/4hfpuu4yt7yk6

The failure seems to happen in the Android Gradle Plugin.
Please open an issue on the Google issue tracker: https://issuetracker.google.com/issues?q=componentid:190923%2B

**Comment by hzsweers** [comment]
Weird! The groovy version I have is working just fine 🤔 . I'll dig more
