### ISSUE TITLE
"Could not generate LightClass for <root> declared in <null>" with Kotlin-DSL in IntelliJ-IDEA

### ISSUE THREAD

**Issue by soberich** [gradle/kotlin-dsl#890]
### Expected Behavior
No constant issue reported

### Current Behavior
100% of times you open Kotlin-DSL Gradle build script there is a IntelliJ error
```java
Could not generate LightClass for <root> declared in <null>
System: Windows 10 10.0 Java Runtime: 1.8.0_152-release-1226-b7: java.lang.AssertionError: 1 trailing arguments were found in org.gradle.kotlin.dsl.support.KotlinScriptHost<org.gradle.api.Project> type
java.lang.IllegalStateException: java.lang.AssertionError: 1 trailing arguments were found in org.gradle.kotlin.dsl.support.KotlinScriptHost<org.gradle.api.Project> type
	at org.jetbrains.kotlin.codegen.CompilationErrorHandler.lambda$static$0(CompilationErrorHandler.java:24)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:74)
	at org.jetbrains.kotlin.asJava.builder.LightClassDataProviderForScript$computeLightClassData$1$1.invoke(LightClassDataProvider.kt:145)
	at org.jetbrains.kotlin.asJava.builder.LightClassDataProviderForScript$computeLightClassData$1$1.invoke(LightClassDataProvider.kt:132)
	at org.jetbrains.kotlin.asJava.builder.LightClassBuilderKt.buildLightClass(LightClassBuilder.kt:58)
	at org.jetbrains.kotlin.asJava.builder.LightClassDataProviderForScript$computeLightClassData$1.invoke(LightClassDataProvider.kt:136)
	at org.jetbrains.kotlin.asJava.builder.LightClassDataProviderForScript$computeLightClassData$1.invoke(LightClassDataProvider.kt:132)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LazyLightClassDataHolder$lazyInexactStub$2.invoke(LazyLightClassDataHolder.kt:59)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LazyLightClassDataHolder$lazyInexactStub$2.invoke(LazyLightClassDataHolder.kt:32)
	at kotlin.SafePublicationLazyImpl.getValue(Lazy.kt:194)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LazyLightClassDataHolder.getLazyInexactStub(LazyLightClassDataHolder.kt)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LazyLightClassDataHolder.getInexactStub(LazyLightClassDataHolder.kt:63)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LazyLightClassDataHolder.access$getInexactStub$p(LazyLightClassDataHolder.kt:32)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LazyLightClassDataHolder$LazyLightClassData$dummyDelegate$2.invoke(LazyLightClassDataHolder.kt:115)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LazyLightClassDataHolder$LazyLightClassData$dummyDelegate$2.invoke(LazyLightClassDataHolder.kt:110)
	at kotlin.SafePublicationLazyImpl.getValue(Lazy.kt:194)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LazyLightClassDataHolder$LazyLightClassData.getDummyDelegate(LazyLightClassDataHolder.kt)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LazyLightClassDataHolder$LazyLightClassData.getOwnFields(LazyLightClassDataHolder.kt:118)
	at org.jetbrains.kotlin.asJava.classes.KtLazyLightClass.getOwnFields(KtLazyLightClass.kt:28)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getAllFields(ClassInnerStuffCache.java:104)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.lambda$getFields$1(ClassInnerStuffCache.java:41)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:140)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:87)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:139)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:126)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getFields(ClassInnerStuffCache.java:41)
	at org.jetbrains.kotlin.asJava.classes.KtLightClassBase.getFields(KtLightClassBase.kt:36)
	at org.jetbrains.uast.UClass$DefaultImpls.getFields(UClass.kt:55)
	at org.jetbrains.uast.UClassTypeSpecific$DefaultImpls.getFields(UClass.kt)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.getFields(KotlinUClass.kt:33)
	at org.jetbrains.uast.kotlin.KotlinScriptUClass.getFields(KotlinUClass.kt:253)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass$uastDeclarations$2.invoke(KotlinUClass.kt:38)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass$uastDeclarations$2.invoke(KotlinUClass.kt:33)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.getUastDeclarations(KotlinUClass.kt)
	at org.jetbrains.uast.UClass$DefaultImpls.accept(UClass.kt:71)
	at org.jetbrains.uast.UClassTypeSpecific$DefaultImpls.accept(UClass.kt)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.accept(KotlinUClass.kt:33)
	at org.jetbrains.uast.internal.ImplementationUtilsKt.acceptList(implementationUtils.kt:23)
	at org.jetbrains.uast.UFile$DefaultImpls.accept(UFile.kt:91)
	at org.jetbrains.uast.kotlin.KotlinUFile.accept(KotlinUFile.kt:30)
	at com.intellij.spring.folding.CodePropertyPlaceholderFoldingBuilder.buildFoldRegions(CodePropertyPlaceholderFoldingBuilder.kt:22)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:71)
	at com.intellij.lang.folding.CompositeFoldingBuilder.buildFoldRegions(CompositeFoldingBuilder.java:43)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:71)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:239)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:225)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getUpdateResult(FoldingUpdate.java:97)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.lambda$updateFoldRegions$0(FoldingUpdate.java:86)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:45)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:96)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.updateFoldRegions(FoldingUpdate.java:82)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegions(CodeFoldingManagerImpl.java:309)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegionsAsync(CodeFoldingManagerImpl.java:295)
	at com.intellij.codeInsight.daemon.impl.CodeFoldingPass.doCollectInformation(CodeFoldingPass.java:42)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.AssertionError: 1 trailing arguments were found in org.gradle.kotlin.dsl.support.KotlinScriptHost<org.gradle.api.Project> type
	at org.jetbrains.kotlin.descriptors.TypeParameterUtilsKt.buildPossiblyInnerType(typeParameterUtils.kt:82)
	at org.jetbrains.kotlin.descriptors.TypeParameterUtilsKt.buildPossiblyInnerType(typeParameterUtils.kt:74)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.writeGenericType(KotlinTypeMapper.java:555)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.lambda$mapType$0(KotlinTypeMapper.java:465)
	at org.jetbrains.kotlin.load.kotlin.TypeSignatureMappingKt.mapType(typeSignatureMapping.kt:156)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapType(KotlinTypeMapper.java:462)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.writeParameterType(KotlinTypeMapper.java:1432)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.writeParameter(KotlinTypeMapper.java:1402)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.writeParameter(KotlinTypeMapper.java:1391)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapScriptSignature(KotlinTypeMapper.java:1576)
	at org.jetbrains.kotlin.codegen.ScriptCodegen.genConstructor(ScriptCodegen.kt:69)
	at org.jetbrains.kotlin.codegen.ScriptCodegen.generateBody(ScriptCodegen.kt:51)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:131)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:115)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:66)
	... 77 more
```

### Steps to Reproduce (for bugs)
Open Koltin-DSL Gradle build script and this failure happens immediately
Though it does NOT interrupt anything else and overall functionality works as expected, the issue notification and report still present.

### Your Environment
see StackTrace above plus on all listed below
IntelliJ IDEA **2018.1.x - 2018.2 EAP** (Ultimate Edition)
Current version which file this issue on is #IU-182.2574.2, built on May 22, 2018
JRE: 1.8.0_152-release-1226-b7 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

with
Gradle **4.6 - 4.9-SNAPSHOT**
JVM:          **1.8.0_162-1.8.0_172**, **9.0.4_11**, **10.0.1** (Oracle Corporation 25.172-b11)
on
OS:           Windows 10 10.0 amd64

P.S.
Please simply comment close this one if it should be reported somewhere else like IntelliJ or IntelliJ-gradle-plugin or gradle itself

**Comment by panjiesw** [comment]
Got bitten by this issue since Gradle 4.6, thought it was issue of Intellij Kotlin plugin.

For me, sometimes it's okay when IDEA launched with Koltin-DSL Gradle build script as current file, but if I change to other build script (in multi module project), the failure happens immediately as above. Some other times, the failure happens immediately regardless the current file being `build.gradle.kts` or not.

My Environment

IDEA: **181.4892.42** 
Plugin: **Kotlin 1.2.41-release-IJ2018.1-1**
Java: **JetBrains s.r.o 1.8.0_152-release** 
Gradle: **4.8-rc-1**
JVM: **1.8.0_172** (OpenJDK 64-Bit Server VM build 25.172-b11)

**Comment by eskatos** [comment]
Please report on [JetBrains Youtrack issue tracker](https://youtrack.jetbrains.com/issues)

**Comment by soberich** [comment]
I'll close then. As I understood this mean their problem and nothing related to kotlin-dsl.
P.S. They have bug filed but with no progress 
https://youtrack.jetbrains.com/issue/KT-23485
